/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Evidential Experiments API
 * OpenAPI spec version: 0.9.0
 */
export type AddExperimentCreatedWebhookRequestDirection = typeof AddExperimentCreatedWebhookRequestDirection[keyof typeof AddExperimentCreatedWebhookRequestDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddExperimentCreatedWebhookRequestDirection = {
  inbound: 'inbound',
  outbound: 'outbound',
} as const;

export type AddExperimentCreatedWebhookRequestUrl = string | null;

export interface AddExperimentCreatedWebhookRequest {
  direction?: AddExperimentCreatedWebhookRequestDirection;
  /** @maxLength 100 */
  name: string;
  type?: 'experiment.created';
  url: AddExperimentCreatedWebhookRequestUrl;
}

export interface AddMemberToOrganizationRequest {
  email: string;
}

export interface AddTurnJourneysChangedWebhookRequest {
  direction?: 'inbound';
  /** @maxLength 100 */
  name: string;
  type?: 'turn.journeys_changed';
}

export type AddWebhookToOrganizationResponseAuthToken = string | null;

export type AddWebhookToOrganizationResponseUrl = string | null;

export interface AddWebhookToOrganizationResponse {
  auth_token: AddWebhookToOrganizationResponseAuthToken;
  direction: string;
  id: string;
  name: string;
  type: string;
  url?: AddWebhookToOrganizationResponseUrl;
}

export type AnyBanditDesignSpecExperimentType = typeof AnyBanditDesignSpecExperimentType[keyof typeof AnyBanditDesignSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnyBanditDesignSpecExperimentType = {
  cmab_online: 'cmab_online',
  mab_online: 'mab_online',
  mab_online_dwh: 'mab_online_dwh',
} as const;

export type AnyBanditDesignSpec = (MABExperimentSpec & {
  experiment_type: AnyBanditDesignSpecExperimentType;
}) | (MABDwhExperimentSpec & {
  experiment_type: AnyBanditDesignSpecExperimentType;
}) | (CMABExperimentSpec & {
  experiment_type: AnyBanditDesignSpecExperimentType;
});

export type AnyFrequentistDesignSpecExperimentType = typeof AnyFrequentistDesignSpecExperimentType[keyof typeof AnyFrequentistDesignSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnyFrequentistDesignSpecExperimentType = {
  freq_online: 'freq_online',
  freq_preassigned: 'freq_preassigned',
} as const;

export type AnyFrequentistDesignSpec = (PreassignedFrequentistExperimentSpec & {
  experiment_type: AnyFrequentistDesignSpecExperimentType;
}) | (OnlineFrequentistExperimentSpec & {
  experiment_type: AnyFrequentistDesignSpecExperimentType;
});

export interface ApiKeySummary {
  /** @maxLength 64 */
  datasource_id: string;
  /** @maxLength 64 */
  id: string;
  /** @maxLength 64 */
  organization_id: string;
  /** @maxLength 100 */
  organization_name: string;
}

export type ApiOnlyDsnType = typeof ApiOnlyDsnType[keyof typeof ApiOnlyDsnType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiOnlyDsnType = {
  api_only: 'api_only',
} as const;

export interface ApiOnlyDsn {
  type: ApiOnlyDsnType;
}

export type ArmArmDescription = string | null;

export type ArmArmId = string | null;

export type ArmArmWeight = ArmWeight | null;

export interface Arm {
  arm_description?: ArmArmDescription;
  arm_id?: ArmArmId;
  /** @maxLength 100 */
  arm_name: string;
  arm_weight?: ArmArmWeight;
}

export type ArmAnalysisArmDescription = string | null;

export type ArmAnalysisArmId = string | null;

export type ArmAnalysisArmWeight = ArmWeight | null;

export type ArmAnalysisCiLower = number | null;

export type ArmAnalysisCiUpper = number | null;

export type ArmAnalysisMeanCiLower = number | null;

export type ArmAnalysisMeanCiUpper = number | null;

export type ArmAnalysisPValue = number | null;

export type ArmAnalysisStdError = number | null;

export type ArmAnalysisTStat = number | null;

export interface ArmAnalysis {
  arm_description?: ArmAnalysisArmDescription;
  arm_id?: ArmAnalysisArmId;
  /** @maxLength 100 */
  arm_name: string;
  arm_weight?: ArmAnalysisArmWeight;
  ci_lower?: ArmAnalysisCiLower;
  ci_upper?: ArmAnalysisCiUpper;
  estimate: number;
  is_baseline: boolean;
  mean_ci_lower?: ArmAnalysisMeanCiLower;
  mean_ci_upper?: ArmAnalysisMeanCiUpper;
  /** @minimum -1 */
  num_missing_values: number;
  p_value: ArmAnalysisPValue;
  std_error: ArmAnalysisStdError;
  t_stat: ArmAnalysisTStat;
}

export type ArmBanditAlpha = number | null;

export type ArmBanditAlphaInit = number | null;

export type ArmBanditArmDescription = string | null;

export type ArmBanditArmId = string | null;

export type ArmBanditArmWeight = ArmWeight | null;

export type ArmBanditBeta = number | null;

export type ArmBanditBetaInit = number | null;

export type ArmBanditCovariance = number[][] | null;

export type ArmBanditMu = number[] | null;

export type ArmBanditMuInit = number | null;

export type ArmBanditSigmaInit = number | null;

export interface ArmBandit {
  alpha?: ArmBanditAlpha;
  alpha_init?: ArmBanditAlphaInit;
  arm_description?: ArmBanditArmDescription;
  arm_id?: ArmBanditArmId;
  /** @maxLength 100 */
  arm_name: string;
  arm_weight?: ArmBanditArmWeight;
  beta?: ArmBanditBeta;
  beta_init?: ArmBanditBetaInit;
  covariance?: ArmBanditCovariance;
  mu?: ArmBanditMu;
  mu_init?: ArmBanditMuInit;
  sigma_init?: ArmBanditSigmaInit;
}

export type ArmSizeClusterCount = number | null;

export interface ArmSize {
  arm: Arm;
  cluster_count?: ArmSizeClusterCount;
  size?: number;
}

/**
 */
export type ArmWeight = number;

export type AssignSummaryArmSizes = ArmSize[] | null;

export type AssignSummaryBalanceCheck = BalanceCheck | null;

export interface AssignSummary {
  arm_sizes?: AssignSummaryArmSizes;
  balance_check?: AssignSummaryBalanceCheck;
  sample_size: number;
}

export type AssignmentAutofailedOutcome = boolean | null;

export type AssignmentClusterKey = string | null;

export type AssignmentContextValues = number[] | null;

export type AssignmentCreatedAt = string | null;

export type AssignmentObservedAt = string | null;

export type AssignmentOutcome = number | null;

export type AssignmentStrata = Strata[] | null;

export interface Assignment {
  arm_id: string;
  /** @maxLength 100 */
  arm_name: string;
  autofailed_outcome?: AssignmentAutofailedOutcome;
  cluster_key?: AssignmentClusterKey;
  context_values?: AssignmentContextValues;
  created_at?: AssignmentCreatedAt;
  observed_at?: AssignmentObservedAt;
  outcome?: AssignmentOutcome;
  /** @maxLength 64 */
  participant_id: string;
  strata?: AssignmentStrata;
}

export interface BalanceCheck {
  balance_ok: boolean;
  denominator_df: number;
  f_statistic: number;
  numerator_df: number;
  p_value: number;
}

export type BanditArmAnalysisAlpha = number | null;

export type BanditArmAnalysisAlphaInit = number | null;

export type BanditArmAnalysisArmDescription = string | null;

export type BanditArmAnalysisArmId = string | null;

export type BanditArmAnalysisArmWeight = ArmWeight | null;

export type BanditArmAnalysisBeta = number | null;

export type BanditArmAnalysisBetaInit = number | null;

export type BanditArmAnalysisCovariance = number[][] | null;

export type BanditArmAnalysisMu = number[] | null;

export type BanditArmAnalysisMuInit = number | null;

export type BanditArmAnalysisSigmaInit = number | null;

export interface BanditArmAnalysis {
  alpha?: BanditArmAnalysisAlpha;
  alpha_init?: BanditArmAnalysisAlphaInit;
  arm_description?: BanditArmAnalysisArmDescription;
  arm_id?: BanditArmAnalysisArmId;
  /** @maxLength 100 */
  arm_name: string;
  arm_weight?: BanditArmAnalysisArmWeight;
  beta?: BanditArmAnalysisBeta;
  beta_init?: BanditArmAnalysisBetaInit;
  covariance?: BanditArmAnalysisCovariance;
  mu?: BanditArmAnalysisMu;
  mu_init?: BanditArmAnalysisMuInit;
  post_pred_ci_lower: number;
  post_pred_ci_upper: number;
  post_pred_mean: number;
  post_pred_stdev: number;
  prior_pred_ci_lower: number;
  prior_pred_ci_upper: number;
  prior_pred_mean: number;
  prior_pred_stdev: number;
  sigma_init?: BanditArmAnalysisSigmaInit;
}

export type BanditExperimentAnalysisResponseContexts = number[] | null;

export type BanditExperimentAnalysisResponseType = typeof BanditExperimentAnalysisResponseType[keyof typeof BanditExperimentAnalysisResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BanditExperimentAnalysisResponseType = {
  bandit: 'bandit',
} as const;

export interface BanditExperimentAnalysisResponse {
  arm_analyses: BanditArmAnalysis[];
  contexts?: BanditExperimentAnalysisResponseContexts;
  created_at: string;
  experiment_id: string;
  fraction_automatically_failed?: number;
  n_outcomes: number;
  type: BanditExperimentAnalysisResponseType;
}

export type BqDsnCredentials = GcpServiceAccount | Hidden;

export type BqDsnType = typeof BqDsnType[keyof typeof BqDsnType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BqDsnType = {
  bigquery: 'bigquery',
} as const;

export interface BqDsn {
  credentials: BqDsnCredentials;
  /**
   * @minLength 1
   * @maxLength 1024
   * @pattern ^[a-zA-Z0-9_]+$
   */
  dataset_id: string;
  /**
   * @minLength 6
   * @maxLength 30
   * @pattern ^[a-z0-9-]+$
   */
  project_id: string;
  type: BqDsnType;
}

export type CMABContextInputRequestContextInputs = ContextInput[] | null;

export interface CMABContextInputRequest {
  context_inputs: CMABContextInputRequestContextInputs;
  type?: 'cmab_assignment';
}

export type CMABExperimentSpecContexts = Context[] | null;

export type CMABExperimentSpecDesignUrl = string | null;

export type CMABExperimentSpecExperimentType = typeof CMABExperimentSpecExperimentType[keyof typeof CMABExperimentSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CMABExperimentSpecExperimentType = {
  cmab_online: 'cmab_online',
} as const;

export interface CMABExperimentSpec {
  /**
   * @minItems 2
   * @maxItems 20
   */
  arms: ArmBandit[];
  autofail_outcome_value?: number;
  /** @minimum 1 */
  autofail_window?: number;
  contexts?: CMABExperimentSpecContexts;
  /** @maxLength 2000 */
  description: string;
  design_url?: CMABExperimentSpecDesignUrl;
  enable_autofail?: boolean;
  end_date: string;
  /** @maxLength 100 */
  experiment_name: string;
  experiment_type: CMABExperimentSpecExperimentType;
  prior_type?: PriorTypes;
  reward_type?: LikelihoodTypes;
  start_date: string;
}

export interface CallbackRequest {
  code: string;
  /**
   * @minLength 43
   * @maxLength 128
   * @pattern ^[A-Za-z0-9._~-]+$
   */
  code_verifier: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  nonce: string;
}

export interface CallbackResponse {
  session_token: string;
}

export interface CallerIdentity {
  email: string;
  hd: string;
  is_privileged: boolean;
  iss: string;
  sub: string;
}

export type ColumnDeletedType = typeof ColumnDeletedType[keyof typeof ColumnDeletedType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ColumnDeletedType = {
  column_deleted: 'column_deleted',
} as const;

export interface ColumnDeleted {
  column_name: string;
  table_name: string;
  type: ColumnDeletedType;
}

export type ContextContextDescription = string | null;

export type ContextContextId = string | null;

export interface Context {
  context_description?: ContextContextDescription;
  context_id?: ContextContextId;
  /** @maxLength 100 */
  context_name: string;
  value_type?: ContextType;
}

export interface ContextInput {
  context_id: string;
  context_value: number;
}

export type ContextType = typeof ContextType[keyof typeof ContextType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContextType = {
  binary: 'binary',
  'real-valued': 'real-valued',
} as const;

export interface CreateApiKeyResponse {
  datasource_id: string;
  /** @maxLength 64 */
  id: string;
  key: string;
}

export interface CreateDatasourceRequest {
  dsn: Dsn;
  name: string;
  /** @maxLength 64 */
  organization_id: string;
}

export interface CreateDatasourceResponse {
  /** @maxLength 64 */
  id: string;
}

export type CreateExperimentRequestPowerAnalyses = PowerResponse | null;

export interface CreateExperimentRequest {
  design_spec: DesignSpec;
  power_analyses?: CreateExperimentRequestPowerAnalyses;
  webhooks?: string[];
}

export type CreateExperimentResponseAssignSummary = AssignSummary | null;

export type CreateExperimentResponsePowerAnalyses = PowerResponse | null;

export type CreateExperimentResponseStoppedAssignmentsAt = string | null;

export type CreateExperimentResponseStoppedAssignmentsReason = StopAssignmentReason | null;

export interface CreateExperimentResponse {
  assign_summary: CreateExperimentResponseAssignSummary;
  datasource_id: string;
  decision?: string;
  design_spec: DesignSpec;
  experiment_id: string;
  impact?: Impact;
  power_analyses: CreateExperimentResponsePowerAnalyses;
  state: ExperimentState;
  stopped_assignments_at: CreateExperimentResponseStoppedAssignmentsAt;
  stopped_assignments_reason: CreateExperimentResponseStoppedAssignmentsReason;
  webhooks?: string[];
}

export interface CreateOrganizationRequest {
  /** @maxLength 100 */
  name: string;
}

export interface CreateOrganizationResponse {
  /** @maxLength 64 */
  id: string;
}

export interface CreateParticipantsTypeRequest {
  /** @maxLength 100 */
  participant_type: string;
  schema_def: ParticipantsSchema;
}

export interface CreateParticipantsTypeResponse {
  /** @maxLength 100 */
  participant_type: string;
  schema_def: ParticipantsSchema;
}

export interface CreateSnapshotResponse {
  id: string;
}

export interface CreateUserRequest {
  /** @maxLength 64 */
  email: string;
}

export interface CreateUserResponse {
  /** @maxLength 64 */
  id: string;
}

export type DataType = typeof DataType[keyof typeof DataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataType = {
  boolean: 'boolean',
  character_varying: 'character varying',
  uuid: 'uuid',
  date: 'date',
  integer: 'integer',
  double_precision: 'double precision',
  numeric: 'numeric',
  timestamp_without_time_zone: 'timestamp without time zone',
  timestamp_with_time_zone: 'timestamp with time zone',
  bigint: 'bigint',
  jsonb: 'jsonb',
  json: 'json',
  unknown: 'unknown',
} as const;

export interface DatasourceSummary {
  driver: string;
  /** @maxLength 64 */
  id: string;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 64 */
  organization_id: string;
  /** @maxLength 100 */
  organization_name: string;
  type: string;
}

export type DeleteExperimentDataRequestAssignments = boolean | null;

export type DeleteExperimentDataRequestSnapshots = boolean | null;

export interface DeleteExperimentDataRequest {
  assignments?: DeleteExperimentDataRequestAssignments;
  snapshots?: DeleteExperimentDataRequestSnapshots;
}

export type DesignSpec = AnyFrequentistDesignSpec | AnyBanditDesignSpec;

export type DesignSpecMetricAvailableN = number | null;

export type DesignSpecMetricAvailableNonnullN = number | null;

export type DesignSpecMetricAvgClusterSize = number | null;

export type DesignSpecMetricCv = number | null;

export type DesignSpecMetricIcc = number | null;

export type DesignSpecMetricMetricBaseline = number | null;

export type DesignSpecMetricMetricPctChange = number | null;

export type DesignSpecMetricMetricStddev = number | null;

export type DesignSpecMetricMetricTarget = number | null;

export type DesignSpecMetricMetricType = MetricType | null;

export interface DesignSpecMetric {
  available_n?: DesignSpecMetricAvailableN;
  available_nonnull_n?: DesignSpecMetricAvailableNonnullN;
  avg_cluster_size?: DesignSpecMetricAvgClusterSize;
  cv?: DesignSpecMetricCv;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  icc?: DesignSpecMetricIcc;
  metric_baseline?: DesignSpecMetricMetricBaseline;
  metric_pct_change?: DesignSpecMetricMetricPctChange;
  metric_stddev?: DesignSpecMetricMetricStddev;
  metric_target?: DesignSpecMetricMetricTarget;
  metric_type?: DesignSpecMetricMetricType;
}

export type DesignSpecMetricRequestAvailableN = number | null;

export type DesignSpecMetricRequestAvailableNonnullN = number | null;

export type DesignSpecMetricRequestAvgClusterSize = number | null;

export type DesignSpecMetricRequestCv = number | null;

export type DesignSpecMetricRequestIcc = number | null;

export type DesignSpecMetricRequestMetricBaseline = number | null;

export type DesignSpecMetricRequestMetricPctChange = number | null;

export type DesignSpecMetricRequestMetricStddev = number | null;

export type DesignSpecMetricRequestMetricTarget = number | null;

export type DesignSpecMetricRequestMetricType = MetricType | null;

export interface DesignSpecMetricRequest {
  available_n?: DesignSpecMetricRequestAvailableN;
  available_nonnull_n?: DesignSpecMetricRequestAvailableNonnullN;
  avg_cluster_size?: DesignSpecMetricRequestAvgClusterSize;
  cv?: DesignSpecMetricRequestCv;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  icc?: DesignSpecMetricRequestIcc;
  metric_baseline?: DesignSpecMetricRequestMetricBaseline;
  metric_pct_change?: DesignSpecMetricRequestMetricPctChange;
  metric_stddev?: DesignSpecMetricRequestMetricStddev;
  metric_target?: DesignSpecMetricRequestMetricTarget;
  metric_type?: DesignSpecMetricRequestMetricType;
}

export interface Drift {
  schema_diff: TableDiff[];
}

export type Dsn = ApiOnlyDsn | PostgresDsn | BqDsn | RedshiftDsn;

export type EventSummaryDetailsAnyOf = { [key: string]: unknown };

export type EventSummaryDetails = EventSummaryDetailsAnyOf | null;

export type EventSummaryLink = string | null;

export type EventSummaryStatusIcon = typeof EventSummaryStatusIcon[keyof typeof EventSummaryStatusIcon];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventSummaryStatusIcon = {
  success: 'success',
  info: 'info',
  failure: 'failure',
} as const;

export interface EventSummary {
  created_at: string;
  details: EventSummaryDetails;
  id: string;
  link?: EventSummaryLink;
  status_icon?: EventSummaryStatusIcon;
  summary: string;
  type: string;
}

export type ExperimentAnalysisResponse = FreqExperimentAnalysisResponse | BanditExperimentAnalysisResponse;

export type ExperimentConfigAssignSummary = AssignSummary | null;

export type ExperimentConfigPowerAnalyses = PowerResponse | null;

export type ExperimentConfigStoppedAssignmentsAt = string | null;

export type ExperimentConfigStoppedAssignmentsReason = StopAssignmentReason | null;

export interface ExperimentConfig {
  assign_summary: ExperimentConfigAssignSummary;
  datasource_id: string;
  decision?: string;
  design_spec: DesignSpec;
  experiment_id: string;
  impact?: Impact;
  power_analyses: ExperimentConfigPowerAnalyses;
  state: ExperimentState;
  stopped_assignments_at: ExperimentConfigStoppedAssignmentsAt;
  stopped_assignments_reason: ExperimentConfigStoppedAssignmentsReason;
  webhooks?: string[];
}

export type ExperimentState = typeof ExperimentState[keyof typeof ExperimentState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExperimentState = {
  assigned: 'assigned',
  abandoned: 'abandoned',
  committed: 'committed',
} as const;

export type FieldChangedTypeType = typeof FieldChangedTypeType[keyof typeof FieldChangedTypeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldChangedTypeType = {
  column_changed_type: 'column_changed_type',
} as const;

export interface FieldChangedType {
  column_name: string;
  new_type: DataType;
  old_type: DataType;
  table_name: string;
  type: FieldChangedTypeType;
}

export type FieldDescriptorExtraAnyOf = {[key: string]: string};

/**
 * @deprecated
 */
export type FieldDescriptorExtra = FieldDescriptorExtraAnyOf | null;

export interface FieldDescriptor {
  data_type: DataType;
  description?: string;
  /** @deprecated */
  extra?: FieldDescriptorExtra;
  field_name: string;
  is_filter?: boolean;
  is_metric?: boolean;
  is_strata?: boolean;
  is_unique_id?: boolean;
}

export interface FieldMetadata {
  data_type: DataType;
  /** @maxLength 2000 */
  description: string;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
}

export interface Filter {
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  relation: Relation;
  value: FilterValueTypes;
}

export type FilterValueTypesAnyOfItem = string | null;

export type FilterValueTypesAnyOfTwoItem = boolean | null;

export type FilterValueTypes = StrictInt[] | StrictFloat[] | FilterValueTypesAnyOfItem[] | FilterValueTypesAnyOfTwoItem[];

export type FreqExperimentAnalysisResponseNumMissingParticipants = number | null;

export type FreqExperimentAnalysisResponseType = typeof FreqExperimentAnalysisResponseType[keyof typeof FreqExperimentAnalysisResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FreqExperimentAnalysisResponseType = {
  freq: 'freq',
} as const;

export interface FreqExperimentAnalysisResponse {
  created_at: string;
  experiment_id: string;
  metric_analyses: MetricAnalysis[];
  num_missing_participants?: FreqExperimentAnalysisResponseNumMissingParticipants;
  num_participants: number;
  type: FreqExperimentAnalysisResponseType;
}

export interface GcpServiceAccount {
  content: GcpServiceAccountBlob;
  type?: 'serviceaccountinfo';
}

/**
 * @minLength 4
 * @maxLength 8000
 */
export type GcpServiceAccountBlob = string;

export interface GetDatasourceResponse {
  dsn: Dsn;
  /** @maxLength 64 */
  id: string;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 64 */
  organization_id: string;
  /** @maxLength 100 */
  organization_name: string;
}

export type GetExperimentAssignmentsResponseBalanceCheck = BalanceCheck | null;

export interface GetExperimentAssignmentsResponse {
  assignments: Assignment[];
  balance_check?: GetExperimentAssignmentsResponseBalanceCheck;
  experiment_id: string;
  sample_size: number;
}

export type GetExperimentForUiResponseExperimentSchema = ParticipantsSchema | null;

export interface GetExperimentForUiResponse {
  config: ExperimentConfig;
  experiment_schema: GetExperimentForUiResponseExperimentSchema;
}

export type GetExperimentResponseAssignSummary = AssignSummary | null;

export type GetExperimentResponsePowerAnalyses = PowerResponse | null;

export type GetExperimentResponseStoppedAssignmentsAt = string | null;

export type GetExperimentResponseStoppedAssignmentsReason = StopAssignmentReason | null;

export interface GetExperimentResponse {
  assign_summary: GetExperimentResponseAssignSummary;
  datasource_id: string;
  decision?: string;
  design_spec: DesignSpec;
  experiment_id: string;
  impact?: Impact;
  power_analyses: GetExperimentResponsePowerAnalyses;
  state: ExperimentState;
  stopped_assignments_at: GetExperimentResponseStoppedAssignmentsAt;
  stopped_assignments_reason: GetExperimentResponseStoppedAssignmentsReason;
  webhooks?: string[];
}

export type GetFiltersResponseDiscreteDistinctValues = string[] | null;

export interface GetFiltersResponseDiscrete {
  data_type: DataType;
  /** @maxLength 2000 */
  description: string;
  distinct_values: GetFiltersResponseDiscreteDistinctValues;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  relations: Relation[];
}

export type GetFiltersResponseElement = GetFiltersResponseNumericOrDate | GetFiltersResponseDiscrete;

export type GetFiltersResponseNumericOrDateMax = string | string | number | number | null;

export type GetFiltersResponseNumericOrDateMin = string | string | number | number | null;

export interface GetFiltersResponseNumericOrDate {
  data_type: DataType;
  /** @maxLength 2000 */
  description: string;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  max: GetFiltersResponseNumericOrDateMax;
  min: GetFiltersResponseNumericOrDateMin;
  /**
   * @minItems 1
   * @maxItems 20
   */
  relations: Relation[];
}

export interface GetMetricsResponseElement {
  data_type: DataType;
  /** @maxLength 2000 */
  description: string;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
}

export interface GetOrganizationResponse {
  datasources: DatasourceSummary[];
  /** @maxLength 64 */
  id: string;
  /** @maxLength 100 */
  name: string;
  users: UserSummary[];
}

export type GetParticipantAssignmentResponseAssignment = Assignment | null;

export interface GetParticipantAssignmentResponse {
  assignment: GetParticipantAssignmentResponseAssignment;
  experiment_id: string;
  participant_id: string;
}

export interface GetParticipantsTypeResponse {
  current: ParticipantsDef;
  drift: Drift;
  proposed: ParticipantsDef;
}

export interface GetSnapshotResponse {
  snapshot: Snapshot;
}

export interface GetStrataResponseElement {
  data_type: DataType;
  /** @maxLength 2000 */
  description: string;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
}

export type GetTurnArmJourneyMappingResponseArmToJourneys = {[key: string]: string};

export interface GetTurnArmJourneyMappingResponse {
  arm_to_journeys: GetTurnArmJourneyMappingResponseArmToJourneys;
  stale_arm_ids: string[];
}

export type GetTurnConnectionResponseAuthToken = string | null;

export type GetTurnConnectionResponseUrl = string | null;

export interface GetTurnConnectionResponse {
  auth_token: GetTurnConnectionResponseAuthToken;
  direction: string;
  id: string;
  name: string;
  turn_api_token_preview: string;
  type: string;
  url?: GetTurnConnectionResponseUrl;
}

export interface GetTurnJourneysResponse {
  journeys: Journey[];
}

export interface GetUserResponse {
  created_at: string;
  email: string;
  has_logged_in: boolean;
  id: string;
  is_privileged: boolean;
  last_logout: string;
  organizations: OrganizationListItem[];
}

export interface HTTPExceptionError {
  detail: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export const HiddenValue = {
  type: 'hidden',
} as const;
export type Hidden = typeof HiddenValue;

export type Impact = typeof Impact[keyof typeof Impact];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Impact = {
  high: 'high',
  medium: 'medium',
  low: 'low',
  negative: 'negative',
  unclear: 'unclear',
  '': '',
} as const;

export interface InspectDatasourceResponse {
  tables: string[];
}

export interface InspectDatasourceTableResponse {
  detected_unique_id_fields: string[];
  fields: FieldMetadata[];
  primary_key_fields: string[];
}

export interface InspectParticipantTypesResponse {
  filters: GetFiltersResponseElement[];
  metrics: GetMetricsResponseElement[];
  strata: GetStrataResponseElement[];
}

export interface Journey {
  name: string;
  uuid: string;
}

export type LikelihoodTypes = typeof LikelihoodTypes[keyof typeof LikelihoodTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LikelihoodTypes = {
  binary: 'binary',
  'real-valued': 'real-valued',
} as const;

export interface ListApiKeysResponse {
  items: ApiKeySummary[];
}

export interface ListDatasourcesResponse {
  items: DatasourceSummary[];
}

export interface ListExperimentsResponse {
  items: ExperimentConfig[];
}

export interface ListOrganizationEventsResponse {
  items: EventSummary[];
  next_page_token?: string;
}

export interface ListOrganizationsResponse {
  items: OrganizationListItem[];
  next_page_token?: string;
}

export interface ListParticipantsTypeResponse {
  has_hidden: boolean;
  items: ParticipantsDef[];
}

export type ListSnapshotsResponseLatestFailure = string | null;

export interface ListSnapshotsResponse {
  items: Snapshot[];
  latest_failure: ListSnapshotsResponseLatestFailure;
  next_page_token?: string;
}

export interface ListUsersResponse {
  items: UserDetail[];
  next_page_token?: string;
}

export interface ListWebhooksResponse {
  items: WebhookSummary[];
}

export type MABDwhExperimentSpecContexts = Context[] | null;

export type MABDwhExperimentSpecDesignUrl = string | null;

export type MABDwhExperimentSpecExperimentType = typeof MABDwhExperimentSpecExperimentType[keyof typeof MABDwhExperimentSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MABDwhExperimentSpecExperimentType = {
  mab_online_dwh: 'mab_online_dwh',
} as const;

export interface MABDwhExperimentSpec {
  /**
   * @minItems 2
   * @maxItems 20
   */
  arms: ArmBandit[];
  autofail_outcome_value?: number;
  /** @minimum 1 */
  autofail_window?: number;
  contexts?: MABDwhExperimentSpecContexts;
  /** @maxLength 2000 */
  description: string;
  design_url?: MABDwhExperimentSpecDesignUrl;
  enable_autofail?: boolean;
  end_date: string;
  /** @maxLength 100 */
  experiment_name: string;
  experiment_type: MABDwhExperimentSpecExperimentType;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  primary_key: string;
  prior_type?: PriorTypes;
  reward_type?: LikelihoodTypes;
  start_date: string;
  /** @maxLength 100 */
  table_name: string;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  target_field_name: string;
}

export type MABExperimentSpecContexts = Context[] | null;

export type MABExperimentSpecDesignUrl = string | null;

export type MABExperimentSpecExperimentType = typeof MABExperimentSpecExperimentType[keyof typeof MABExperimentSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MABExperimentSpecExperimentType = {
  mab_online: 'mab_online',
} as const;

export interface MABExperimentSpec {
  /**
   * @minItems 2
   * @maxItems 20
   */
  arms: ArmBandit[];
  autofail_outcome_value?: number;
  /** @minimum 1 */
  autofail_window?: number;
  contexts?: MABExperimentSpecContexts;
  /** @maxLength 2000 */
  description: string;
  design_url?: MABExperimentSpecDesignUrl;
  enable_autofail?: boolean;
  end_date: string;
  /** @maxLength 100 */
  experiment_name: string;
  experiment_type: MABExperimentSpecExperimentType;
  prior_type?: PriorTypes;
  reward_type?: LikelihoodTypes;
  start_date: string;
}

export type MdeCurvePointDesiredNClusters = number | null;

export type MdeCurvePointPctChange = number | null;

export interface MdeCurvePoint {
  desired_n: number;
  desired_n_clusters?: MdeCurvePointDesiredNClusters;
  pct_change?: MdeCurvePointPctChange;
}

export interface MessageError {
  message: string;
}

export interface MetricAnalysis {
  arm_analyses: ArmAnalysis[];
  metric: DesignSpecMetricRequest;
  metric_name: string;
}

export type MetricPowerAnalysisClustersPerArm = number[] | null;

export type MetricPowerAnalysisDesignEffect = number | null;

export type MetricPowerAnalysisEffectiveSampleSize = number | null;

export type MetricPowerAnalysisMdeCurve = MdeCurvePoint[] | null;

export type MetricPowerAnalysisMsg = MetricPowerAnalysisMessage | null;

export type MetricPowerAnalysisNPerArm = number[] | null;

export type MetricPowerAnalysisNumClustersTotal = number | null;

export type MetricPowerAnalysisPctChangePossible = number | null;

export type MetricPowerAnalysisPctChangeWithDesiredN = number | null;

export type MetricPowerAnalysisSufficientN = boolean | null;

export type MetricPowerAnalysisTargetN = number | null;

export type MetricPowerAnalysisTargetPossible = number | null;

export interface MetricPowerAnalysis {
  clusters_per_arm?: MetricPowerAnalysisClustersPerArm;
  design_effect?: MetricPowerAnalysisDesignEffect;
  effective_sample_size?: MetricPowerAnalysisEffectiveSampleSize;
  mde_curve?: MetricPowerAnalysisMdeCurve;
  metric_spec: DesignSpecMetric;
  msg?: MetricPowerAnalysisMsg;
  n_per_arm?: MetricPowerAnalysisNPerArm;
  num_clusters_total?: MetricPowerAnalysisNumClustersTotal;
  pct_change_possible?: MetricPowerAnalysisPctChangePossible;
  pct_change_with_desired_n?: MetricPowerAnalysisPctChangeWithDesiredN;
  sufficient_n?: MetricPowerAnalysisSufficientN;
  target_n?: MetricPowerAnalysisTargetN;
  target_possible?: MetricPowerAnalysisTargetPossible;
}

export type MetricPowerAnalysisMessageValuesAnyOf = {[key: string]: number | number};

export type MetricPowerAnalysisMessageValues = MetricPowerAnalysisMessageValuesAnyOf | null;

export interface MetricPowerAnalysisMessage {
  high_cluster_variation?: boolean;
  msg: string;
  source_msg: string;
  type: MetricPowerAnalysisMessageType;
  values?: MetricPowerAnalysisMessageValues;
}

export type MetricPowerAnalysisMessageType = typeof MetricPowerAnalysisMessageType[keyof typeof MetricPowerAnalysisMessageType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetricPowerAnalysisMessageType = {
  sufficient: 'sufficient',
  insufficient: 'insufficient',
  no_baseline: 'no baseline',
  no_available_n: 'no available n',
  zero_effect_size: 'zero effect size',
  zero_variation: 'zero variation',
} as const;

export type MetricType = typeof MetricType[keyof typeof MetricType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetricType = {
  binary: 'binary',
  numeric: 'numeric',
} as const;

export interface OnlineAssignmentWithFiltersRequest {
  /** Participant properties to match against the experiment's filters. */
  properties: ParticipantProperty[];
}

export type OnlineFrequentistExperimentSpecDesignUrl = string | null;

export type OnlineFrequentistExperimentSpecDesiredN = number | null;

export type OnlineFrequentistExperimentSpecDesiredNs = number[] | null;

export type OnlineFrequentistExperimentSpecExperimentType = typeof OnlineFrequentistExperimentSpecExperimentType[keyof typeof OnlineFrequentistExperimentSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnlineFrequentistExperimentSpecExperimentType = {
  freq_online: 'freq_online',
} as const;

export interface OnlineFrequentistExperimentSpec {
  /**
   * @minimum 0
   * @maximum 1
   */
  alpha?: number;
  /**
   * @minItems 2
   * @maxItems 20
   */
  arms: Arm[];
  /** @maxLength 2000 */
  description: string;
  design_url?: OnlineFrequentistExperimentSpecDesignUrl;
  desired_n?: OnlineFrequentistExperimentSpecDesiredN;
  desired_ns?: OnlineFrequentistExperimentSpecDesiredNs;
  end_date: string;
  /** @maxLength 100 */
  experiment_name: string;
  experiment_type: OnlineFrequentistExperimentSpecExperimentType;
  /** @maxItems 20 */
  filters: Filter[];
  /**
   * @minimum 0
   * @maximum 1
   */
  fstat_thresh?: number;
  /**
   * @minItems 1
   * @maxItems 150
   */
  metrics: DesignSpecMetricRequest[];
  /**
   * @minimum 0
   * @maximum 1
   */
  power?: number;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  primary_key: string;
  start_date: string;
  /** @maxItems 150 */
  strata: Stratum[];
  /** @maxLength 100 */
  table_name: string;
}

export type OrganizationListItemExperimentCount = number | null;

export type OrganizationListItemJoinedAt = string | null;

export type OrganizationListItemUserCount = number | null;

export interface OrganizationListItem {
  created_at: string;
  experiment_count?: OrganizationListItemExperimentCount;
  /** @maxLength 64 */
  id: string;
  joined_at?: OrganizationListItemJoinedAt;
  /** @maxLength 100 */
  name: string;
  user_count?: OrganizationListItemUserCount;
}

export interface OrganizationSummary {
  /** @maxLength 64 */
  id: string;
  /** @maxLength 100 */
  name: string;
}

export interface ParticipantProperty {
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  value: PropertyValueTypes;
}

export interface ParticipantsDef {
  fields: FieldDescriptor[];
  hidden?: boolean;
  participant_type: string;
  table_name: string;
  type: 'schema';
}

export interface ParticipantsSchema {
  fields: FieldDescriptor[];
  table_name: string;
}

export type PatchUserRequestIsPrivileged = boolean | null;

export interface PatchUserRequest {
  is_privileged?: PatchUserRequestIsPrivileged;
}

export type PostgresDsnPassword = RevealedStr | Hidden;

export type PostgresDsnSearchPath = string | null;

export type PostgresDsnSslmode = typeof PostgresDsnSslmode[keyof typeof PostgresDsnSslmode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgresDsnSslmode = {
  disable: 'disable',
  require: 'require',
  'verify-ca': 'verify-ca',
  'verify-full': 'verify-full',
} as const;

export type PostgresDsnType = typeof PostgresDsnType[keyof typeof PostgresDsnType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostgresDsnType = {
  postgres: 'postgres',
} as const;

export interface PostgresDsn {
  dbname: string;
  host: string;
  password: PostgresDsnPassword;
  /**
   * @minimum 1024
   * @maximum 65535
   */
  port: number;
  search_path: PostgresDsnSearchPath;
  sslmode: PostgresDsnSslmode;
  type: PostgresDsnType;
  user: string;
}

export interface PowerRequest {
  design_spec: AnyFrequentistDesignSpec;
}

export interface PowerResponse {
  /** @maxItems 150 */
  analyses: MetricPowerAnalysis[];
}

export type PreassignedFrequentistExperimentSpecClusterKey = string | null;

export type PreassignedFrequentistExperimentSpecDesignUrl = string | null;

export type PreassignedFrequentistExperimentSpecDesiredN = number | null;

export type PreassignedFrequentistExperimentSpecDesiredNClusters = number | null;

export type PreassignedFrequentistExperimentSpecDesiredNs = number[] | null;

export type PreassignedFrequentistExperimentSpecDesiredNsClusters = number[] | null;

export type PreassignedFrequentistExperimentSpecExperimentType = typeof PreassignedFrequentistExperimentSpecExperimentType[keyof typeof PreassignedFrequentistExperimentSpecExperimentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreassignedFrequentistExperimentSpecExperimentType = {
  freq_preassigned: 'freq_preassigned',
} as const;

export interface PreassignedFrequentistExperimentSpec {
  /**
   * @minimum 0
   * @maximum 1
   */
  alpha?: number;
  /**
   * @minItems 2
   * @maxItems 20
   */
  arms: Arm[];
  cluster_key?: PreassignedFrequentistExperimentSpecClusterKey;
  /** @maxLength 2000 */
  description: string;
  design_url?: PreassignedFrequentistExperimentSpecDesignUrl;
  desired_n?: PreassignedFrequentistExperimentSpecDesiredN;
  desired_n_clusters?: PreassignedFrequentistExperimentSpecDesiredNClusters;
  desired_ns?: PreassignedFrequentistExperimentSpecDesiredNs;
  desired_ns_clusters?: PreassignedFrequentistExperimentSpecDesiredNsClusters;
  end_date: string;
  /** @maxLength 100 */
  experiment_name: string;
  experiment_type: PreassignedFrequentistExperimentSpecExperimentType;
  /** @maxItems 20 */
  filters: Filter[];
  /**
   * @minimum 0
   * @maximum 1
   */
  fstat_thresh?: number;
  /**
   * @minItems 1
   * @maxItems 150
   */
  metrics: DesignSpecMetricRequest[];
  /**
   * @minimum 0
   * @maximum 1
   */
  power?: number;
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  primary_key: string;
  start_date: string;
  /** @maxItems 150 */
  strata: Stratum[];
  /** @maxLength 100 */
  table_name: string;
}

export type PriorTypes = typeof PriorTypes[keyof typeof PriorTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PriorTypes = {
  beta: 'beta',
  normal: 'normal',
} as const;

export type PropertyValueTypes = StrictInt | StrictFloat | string | boolean | null;

export type RedshiftDsnPassword = RevealedStr | Hidden;

export type RedshiftDsnSearchPath = string | null;

export type RedshiftDsnType = typeof RedshiftDsnType[keyof typeof RedshiftDsnType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedshiftDsnType = {
  redshift: 'redshift',
} as const;

export interface RedshiftDsn {
  dbname: string;
  host: string;
  password: RedshiftDsnPassword;
  /**
   * @minimum 1024
   * @maximum 65535
   */
  port: number;
  search_path: RedshiftDsnSearchPath;
  type: RedshiftDsnType;
  user: string;
}

export type Relation = typeof Relation[keyof typeof Relation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Relation = {
  includes: 'includes',
  excludes: 'excludes',
  between: 'between',
} as const;

export interface RevealedStr {
  type?: 'revealed';
  value: string;
}

export type SampleCallBodyAnyOf = { [key: string]: unknown };

export type SampleCallBody = SampleCallBodyAnyOf | null;

export type SampleCallExampleResponseAnyOf = { [key: string]: unknown };

export type SampleCallExampleResponse = SampleCallExampleResponseAnyOf | null;

/**
 * Request headers; secrets are placeholders, never real values.
 */
export type SampleCallHeaders = {[key: string]: string};

export interface SampleCall {
  body?: SampleCallBody;
  example_response?: SampleCallExampleResponse;
  /** Request headers; secrets are placeholders, never real values. */
  headers: SampleCallHeaders;
  label: string;
  method: string;
  path: string;
}

export interface SampleCalls {
  calls: SampleCall[];
}

export interface SetConnectionToTurnRequest {
  /** @minLength 335 */
  turn_api_token: string;
}

export type SetTurnArmJourneyMappingRequestArmToJourneys = {[key: string]: string};

export interface SetTurnArmJourneyMappingRequest {
  arm_to_journeys: SetTurnArmJourneyMappingRequestArmToJourneys;
}

export type SnapshotData = ExperimentAnalysisResponse | null;

export type SnapshotDetailsAnyOf = { [key: string]: unknown };

export type SnapshotDetails = SnapshotDetailsAnyOf | null;

export interface Snapshot {
  created_at: string;
  data: SnapshotData;
  details: SnapshotDetails;
  experiment_id: string;
  id: string;
  status: SnapshotStatus;
  updated_at: string;
}

export type SnapshotStatus = typeof SnapshotStatus[keyof typeof SnapshotStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SnapshotStatus = {
  success: 'success',
  running: 'running',
  failed: 'failed',
} as const;

export type StopAssignmentReason = typeof StopAssignmentReason[keyof typeof StopAssignmentReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StopAssignmentReason = {
  preassigned: 'preassigned',
  end_date: 'end_date',
  manual: 'manual',
  target_n: 'target_n',
} as const;

export type StrataStrataValue = string | null;

export interface Strata {
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
  strata_value?: StrataStrataValue;
}

export interface Stratum {
  /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
  field_name: string;
}

export type StrictFloat = number | null;

export type StrictInt = number | null;

export type TableDeletedType = typeof TableDeletedType[keyof typeof TableDeletedType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableDeletedType = {
  table_deleted: 'table_deleted',
} as const;

export interface TableDeleted {
  table_name: string;
  type: TableDeletedType;
}

export type TableDiff = ColumnDeleted | FieldChangedType | TableDeleted;

export type TurnConfigResponseArmJourneyMap = {[key: string]: string};

export interface TurnConfigResponse {
  arm_journey_map: TurnConfigResponseArmJourneyMap;
  experiment_id: string;
  experiment_name: string;
}

export type UpdateArmRequestDescription = string | null;

export type UpdateArmRequestName = string | null;

export interface UpdateArmRequest {
  description?: UpdateArmRequestDescription;
  name?: UpdateArmRequestName;
}

export interface UpdateBanditArmOutcomeRequest {
  outcome: number;
}

export type UpdateDatasourceRequestDsn = Dsn | null;

export type UpdateDatasourceRequestName = string | null;

export interface UpdateDatasourceRequest {
  dsn?: UpdateDatasourceRequestDsn;
  name?: UpdateDatasourceRequestName;
}

export type UpdateExperimentRequestDecision = string | null;

export type UpdateExperimentRequestDescription = string | null;

export type UpdateExperimentRequestDesignUrl = string | null;

export type UpdateExperimentRequestEndDate = string | null;

export type UpdateExperimentRequestImpact = Impact | null;

export type UpdateExperimentRequestName = string | null;

export type UpdateExperimentRequestStartDate = string | null;

export interface UpdateExperimentRequest {
  decision?: UpdateExperimentRequestDecision;
  description?: UpdateExperimentRequestDescription;
  design_url?: UpdateExperimentRequestDesignUrl;
  end_date?: UpdateExperimentRequestEndDate;
  impact?: UpdateExperimentRequestImpact;
  name?: UpdateExperimentRequestName;
  start_date?: UpdateExperimentRequestStartDate;
}

export type UpdateOrganizationRequestName = string | null;

export interface UpdateOrganizationRequest {
  name?: UpdateOrganizationRequestName;
}

export interface UpdateOrganizationWebhookRequest {
  /** @maxLength 100 */
  name: string;
  /** @maxLength 500 */
  url: string;
}

export type UpdateParticipantsTypeRequestFields = FieldDescriptor[] | null;

export type UpdateParticipantsTypeRequestParticipantType = string | null;

export type UpdateParticipantsTypeRequestTableName = string | null;

export interface UpdateParticipantsTypeRequest {
  fields?: UpdateParticipantsTypeRequestFields;
  participant_type?: UpdateParticipantsTypeRequestParticipantType;
  table_name?: UpdateParticipantsTypeRequestTableName;
}

export type UpdateParticipantsTypeResponseFields = FieldDescriptor[] | null;

export type UpdateParticipantsTypeResponseTableName = string | null;

export interface UpdateParticipantsTypeResponse {
  fields?: UpdateParticipantsTypeResponseFields;
  /** @maxLength 100 */
  participant_type: string;
  table_name?: UpdateParticipantsTypeResponseTableName;
}

export interface UserDetail {
  created_at: string;
  email: string;
  has_logged_in: boolean;
  id: string;
  is_privileged: boolean;
  last_logout: string;
  organizations: OrganizationSummary[];
}

export interface UserSummary {
  /** @maxLength 64 */
  email: string;
  /** @maxLength 64 */
  id: string;
  is_privileged: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type WebhookSummaryAuthToken = string | null;

export type WebhookSummaryUrl = string | null;

export interface WebhookSummary {
  auth_token: WebhookSummaryAuthToken;
  direction: string;
  id: string;
  name: string;
  type: string;
  url?: WebhookSummaryUrl;
}

export interface XHTTPValidationError {
  detail: XValidationError[];
}

export type XValidationErrorLocItem = string | number;

export interface XValidationError {
  loc: XValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type CreateDatasourceParams = {
connectivity_check?: boolean;
};

export type DeleteApiKeyParams = {
allow_missing?: boolean;
};

export type CreateExperimentParams = {
stratify_on_metrics?: boolean;
};

export type DeleteExperimentParams = {
allow_missing?: boolean;
};

export type AnalyzeExperimentParams = {
baseline_arm_id?: string | null;
};

export type InspectDatasourceParams = {
refresh?: boolean;
};

export type InspectTableInDatasourceParams = {
refresh?: boolean;
};

export type DeleteParticipantParams = {
allow_missing?: boolean;
};

export type InspectParticipantTypesParams = {
refresh?: boolean;
expensive?: boolean;
};

export type GetExperimentSampleCalls200 = SampleCalls | null;

export type DeleteTurnConnectionFromOrganizationParams = {
allow_missing?: boolean;
};

export type GetOrganizationTurnConnectionParams = {
allow_missing?: boolean;
};

export type RegenerateTurnWebhookTokenParams = {
allow_missing?: boolean;
};

export type DeleteTurnArmJourneyMappingParams = {
allow_missing?: boolean;
};

export type ListOrganizationsParams = {
scope?: ListOrganizationsScope;
name_contains?: string | null;
include_stats?: boolean;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
page_token?: string | null;
/**
 * @minimum 0
 */
skip?: number;
};

export type ListOrganizationsScope = typeof ListOrganizationsScope[keyof typeof ListOrganizationsScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListOrganizationsScope = {
  mine: 'mine',
  all: 'all',
} as const;

export type DeleteDatasourceParams = {
allow_missing?: boolean;
};

export type ListSnapshotsParams = {
status?: SnapshotStatus[] | null;
/**
 * @minimum 1
 */
page_size?: number;
page_token?: string | null;
/**
 * @minimum 0
 */
skip?: number;
};

export type DeleteSnapshotParams = {
allow_missing?: boolean;
};

export type ListOrganizationEventsParams = {
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
page_token?: string | null;
/**
 * @minimum 0
 */
skip?: number;
};

export type RemoveMemberFromOrganizationParams = {
allow_missing?: boolean;
};

export type AddWebhookToOrganizationBody = AddExperimentCreatedWebhookRequest | AddTurnJourneysChangedWebhookRequest;

export type DeleteWebhookFromOrganizationParams = {
allow_missing?: boolean;
};

export type ListUsersParams = {
email_contains?: string | null;
scope?: ListUsersScope;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
page_token?: string | null;
/**
 * @minimum 0
 */
skip?: number;
};

export type ListUsersScope = typeof ListUsersScope[keyof typeof ListUsersScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersScope = {
  all: 'all',
  mine: 'mine',
} as const;

